" The usual suspects
syntax on
set number
set t_Co=256
set nobackup
set nowritebackup

" Defaults for tabs and spaces
set tabstop=4
set shiftwidth=4
set expandtab
set backspace=2

" HTML files
au FileType html set tabstop=2 shiftwidth=2

" Print red characters after 80 limit
highlight OverLength ctermfg=red
match OverLength /\%81v.\+/
