# Git prompt 
source ~/.git-prompt.sh

# Custom prompt
autoload -U colors && colors
setopt prompt_subst

PROMPT="%B%n@%M%b \$(__git_ps1)
%F{1}>%f "

RPROMPT="%B%~/%b"

# Aliases
alias 'll'='ls -l --color=auto'
alias 'la'='ll -a'
alias '..'='cd ..'
alias '...'='cd ../../'
